name: Running Locust Load Test

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'target environment'
        required: true
        default: 'github'
        type: choice
        options:
        - github
        - aws
        - azure
      host:
        required: true
        options:
          - https://prod.playback.h264.io
        default: "https://prod.playback.h264.io"
        description: "Host"
      endpoint:
        required: true
        default: "integration"
        description: "ex. integration, nightly, gqa_core_test, regression"
      users:
        required: true
        default: " "
        description: "The Number of users against  you want to execute test"
      spawn-rate:
        description: 'spawn-rate according to which you want to execute the load test'
        required: true
        default: " "
      run-time:
        description: 'run-time you want to execute the test for specific time period.'
        required: true
        default: " "
    push:
      branches:
      - main
      - test
      - dev    
env:
  LOCUSTFILE: ${{ github.event.input.LOCUSTFILE }}
  URL: ${{ github.event.input.URL }}
  RATE: ${{ github.event.input.RATE }}
  USERS: ${{ github.event.input.USERS }}
  RUNTIME: ${{ github.event.input.RUNTIME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Load Test
        uses: actions/checkout@v1
        with:
          LOCUSTFILE: locustfile
          URL:  url
          USERS: users
          RATE: rate
          RUNTIME: runtime
          

