name: Running Test

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'target environment'
        required: true
        default: 'github'
        type: choice
        options:
        - github
        - aws
        - azure
      host:
        required: true
        options:
          - https://prod.playback.h264.io
        default: "https://prod.playback.h264.io"
        description: "client under beam. https://prod.playback.h264.io"
      endpoint:
        required: true
        default: "integration"
        description: "ex. integration, nightly, gqa_core_test, regression"
      users:
        required: true
        default: "0 - 1000000"
        description: "The Number of users you want to test"
      spawn-rate:
        description: 'swapn-rate according to which you want to execute the load test'
        required: true
        default: '0s - 50s'
        type: choice
        options:
        - 10s
        - 20s
        - 50s
      run-time:
        description: 'run-time you want to execute the test for specific time period.'
        required: true
        default: '10s - 43200s'
        type: choice
        options:
        - ***
        - ***
        - *** 
    push:
      branches:
      - main
      - test
      - dev    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Load Test
        uses: vipin-discovery/Demo-locust-github-action@main
        with:
          LOCUSTFILE: "locustfile.py"
          URL:  "https://prod.playback.h264.io"
          USERS: "6"
          RATE: "6"
          RUNTIME: "10s"