name: Running Locust Load Test

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'target environment'
        required: true
        default: 'github'
        type: choice
        options:
        - github
        - aws
        - azure
      host:
        required: true
        options:
          - https://prod.playback.h264.io
        default: "https://prod.playback.h264.io"
        description: "Host"
      endpoint:
        required: true
        default: "integration"
        description: "ex. integration, nightly, gqa_core_test, regression"
      users:
        required: true
        default: "1"
        description: "The Number of users against  you want to execute test"
      spawn-rate:
        description: 'spawn-rate according to which you want to execute the load test'
        required: true
        default: "1"
      run-time:
        description: 'run-time you want to execute the test for specific time period.'
        required: true
        default: "10s"
    push:
      branches:
      - main
      - test
      - dev    
env:
  LOCUSTFILE: ${{ secrets.LOCUSTFILE }}
  URL: ${{ secrets.URL }}
  RATE: ${{ secrets.RATE }}
  USERS: ${{ secrets.USERS }}
  RUNTIME: ${{ secrets.RUNTIME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Load Test
        uses: vipin-discovery/load-test-pipeline@dev1
        with:
          LOCUSTFILE: ${{env.locustfile}}
          URL:  ${{env.url}}
          USERS: ${{env.users}}
          RATE: ${{env.rate}}
          RUNTIME: ${{env.runtime}}
          

