name: Running Locust Load Test

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'target environment'
        required: true
        default: 'github'
        type: choice
        options:
        - github
        - aws
        - azure
      host:
        required: true
        options:
          - https://prod.playback.h264.io
        default: "https://prod.playback.h264.io"
        description: "Host"
      endpoint:
        required: true
        default: "integration"
        description: "endpoint"
      users:
        required: true
        type: choice
        options:
          - "1000"
          - "5000"
          - "10000"
        default: "5"
        description: "Number of users"
      spawn-rate:
        description: "spawn-rate"
        type: choice
        options:
          - "1"
          - "2"
          - "5"
        required: true
        default: "5"
      run-time:
        description: 'run-time'
        type: choice
        options:
          - "5s"
          - "10s"
          - "30s"
          - "60s"
        required: true
        default: "10s"
    push:
      branches:
      - main
      - test
      - dev 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_840220838417 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_840220838417}}
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN_840220838417 }}
          role-duration-seconds: 900
          aws-region: us-east-1  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Load Test
        uses: vipin-discovery/load-test-pipeline@dev1
        with:
          LOCUSTFILE: "locustfile.py"
          URL:  "https://prod.playback.h264.io"
          USERS: ${{ github.event.input.users }}
          RATE: ${{ github.event.input.spawn-rate }}
          RUNTIME: ${{ github.event.input.run-time }}
          

