name: Running Locust Load Test

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'target environment'
        required: true
        default: 'github'
        type: choice
        options:
        - github
        - aws
        - azure
      host:
        required: true
        options:
          - https://prod.playback.h264.io
        default: "https://prod.playback.h264.io"
        description: "client under beam. https://prod.playback.h264.io"
      endpoint:
        required: true
        default: "integration"
        description: "ex. integration, nightly, gqa_core_test, regression"
      users:
        required: true
        default: " "
        description: "The Number of users for you want to test"
      spawn-rate:
        description: 'swapn-rate according to which you want to execute the load test'
        required: true
        default: " "
      run-time:
        description: 'run-time you want to execute the test for specific time period.'
        required: true
        default: " "
    push:
      branches:
      - main
      - test
      - dev    
env:
  URL: ${{secrert.URL}}
  RATE: ${{secrets.RATE}}
  USERS: ${{secrets.USERS}}
  RUNTIME: ${{scerets.RUNTIME}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Load Test
        uses: actions/checkout@v2
        with:
          LOCUSTFILE: "locustfile.py"
          URL:  URL
          USERS: USERS
          RATE: RATE
          RUNTIME: RUNTIME
          

